class SholatSunnah {
  final String name;
  final String category;
  final String niatArab;
  final String niatLatin;
  final String niatTranslation;
  final String tataCara;
  final String? doaAfter;
  final String? fadhilah;

  SholatSunnah({
    required this.name,
    required this.category,
    required this.niatArab,
    required this.niatLatin,
    required this.niatTranslation,
    required this.tataCara,
    this.doaAfter,
    this.fadhilah,
  });
}

class SholatSunnahData {
  static List<SholatSunnah> sunnahList = [
    // 0. Salat Wajib
    SholatSunnah(
      name: "Salat Subuh",
      category: "Salat Wajib",
      niatArab: "أُصَلِّي فَرْضَ الصُّبْحِ رَكْعَتَيْنِ مُسْتَقْبِلَ الْقِبْلَةِ أَدَاءً لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli fardhash shubhi rak'ataini mustaqbilal qiblati ada'an lillahi ta'ala.",
      niatTranslation: "Aku niat melakukan shalat fardhu subuh dua rakaat, sambil menghadap kiblat, saat ini, karena Allah ta'ala.",
      tataCara: "2 Rakaat dengan Qunut (opsional).",
    ),
    SholatSunnah(
      name: "Salat Dzuhur",
      category: "Salat Wajib",
      niatArab: "أُصَلِّي فَرْضَ الظُّهْرِ أَرْبَعَ رَكَعَاتٍ مُسْتَقْبِلَ الْقِبْلَةِ أَدَاءً لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli fardhadz dzuhri arba'a raka'atin mustaqbilal qiblati ada'an lillahi ta'ala.",
      niatTranslation: "Aku niat melakukan shalat fardhu dzuhur empat rakaat, sambil menghadap kiblat, saat ini, karena Allah ta'ala.",
      tataCara: "4 Rakaat dengan suara pelan (Sirr).",
    ),
    SholatSunnah(
      name: "Salat Ashar",
      category: "Salat Wajib",
      niatArab: "أُصَلِّي فَرْضَ الْعَصْرِ أَرْبَعَ رَكَعَاتٍ مُسْتَقْبِلَ الْقِبْلَةِ أَدَاءً لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli fardhal 'ashri arba'a raka'atin mustaqbilal qiblati ada'an lillahi ta'ala.",
      niatTranslation: "Aku niat melakukan shalat fardhu ashar empat rakaat, sambil menghadap kiblat, saat ini, karena Allah ta'ala.",
      tataCara: "4 Rakaat dengan suara pelan (Sirr).",
    ),
    SholatSunnah(
      name: "Salat Maghrib",
      category: "Salat Wajib",
      niatArab: "أُصَلِّي فَرْضَ الْمَغْرِبِ ثَلاثَ رَكَعَاتٍ مُسْتَقْبِلَ الْقِبْلَةِ أَدَاءً لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli fardhal maghribi tsalatsa raka'atin mustaqbilal qiblati ada'an lillahi ta'ala.",
      niatTranslation: "Aku niat melakukan shalat fardhu maghrib tiga rakaat, sambil menghadap kiblat, saat ini, karena Allah ta'ala.",
      tataCara: "3 Rakaat dengan suara keras (Jahr) di 2 rakaat pertama.",
    ),
    SholatSunnah(
      name: "Salat Isya",
      category: "Salat Wajib",
      niatArab: "أُصَلِّي فَرْضَ الْعِشَاءِ أَرْبَعَ رَكَعَاتٍ مُسْتَقْبِلَ الْقِبْلَةِ أَدَاءً لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli fardhal 'isyaa-i arba'a raka'atin mustaqbilal qiblati ada'an lillahi ta'ala.",
      niatTranslation: "Aku niat melakukan shalat fardhu isya empat rakaat, sambil menghadap kiblat, saat ini, karena Allah ta'ala.",
      tataCara: "4 Rakaat dengan suara keras (Jahr) di 2 rakaat pertama.",
    ),
    // 1. Salat Sunnah Rawatib
    SholatSunnah(
      name: "Qabliyah Subuh",
      category: "Rawatib",
      niatArab: "أُصَلِّي سُنَّةَ الصُّبْحِ رَكْعَتَيْنِ قَبْلِيَّةً لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatash shubhi rak'ataini qabliyyatan lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah sebelum Subuh dua rakaat karena Allah Ta'ala.",
      tataCara: "Dilakukan 2 rakaat sebelum shalat fardu Subuh.",
      fadhilah: "Lebih baik dari dunia dan seisinya.",
    ),
    SholatSunnah(
      name: "Qabliyah Dzuhur",
      category: "Rawatib",
      niatArab: "أُصَلِّي سُنَّةَ الظُّهْرِ رَكْعَتَيْنِ قَبْلِيَّةً لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatadh dhuhri rak'ataini qabliyyatan lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah sebelum Dzuhur dua rakaat karena Allah Ta'ala.",
      tataCara: "Dilakukan 2 atau 4 rakaat sebelum shalat fardu Dzuhur.",
      fadhilah: "Mengharamkan diri dari api neraka.",
    ),
    SholatSunnah(
      name: "Ba'diyyah Dzuhur",
      category: "Rawatib",
      niatArab: "أُصَلِّي سُنَّةَ الظُّهْرِ رَكْعَتَيْنِ بَعْدِيَّةً لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatadh dhuhri rak'ataini ba'diyyatan lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah sesudah Dzuhur dua rakaat karena Allah Ta'ala.",
      tataCara: "Dilakukan 2 atau 4 rakaat sesudah shalat fardu Dzuhur.",
      fadhilah: "Menyempurnakan kekurangan pada shalat fardu.",
    ),
    SholatSunnah(
      name: "Qabliyah Ashar",
      category: "Rawatib",
      niatArab: "أُصَلِّي سُنَّةَ الْعَصْرِ رَكْعَتَيْنِ قَبْلِيَّةً لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatal 'ashri rak'ataini qabliyyatan lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah sebelum Ashar dua rakaat karena Allah Ta'ala.",
      tataCara: "Dilakukan 2 atau 4 rakaat sebelum shalat fardu Ashar.",
      fadhilah: "Mendapat rahmat Allah.",
    ),
    SholatSunnah(
      name: "Qabliyah Maghrib",
      category: "Rawatib",
      niatArab: "أُصَلِّي سُنَّةَ الْمَغْرِبِ رَكْعَتَيْنِ قَبْلِيَّةً لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatal maghribi rak'ataini qabliyyatan lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah sebelum Maghrib dua rakaat karena Allah Ta'ala.",
      tataCara: "Dilakukan 2 rakaat sebelum shalat fardu Maghrib.",
    ),
    SholatSunnah(
      name: "Ba'diyyah Maghrib",
      category: "Rawatib",
      niatArab: "أُصَلِّي سُنَّةَ الْمَغْرِبِ رَكْعَتَيْنِ بَعْدِيَّةً لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatal maghribi rak'ataini ba'diyyatan lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah sesudah Maghrib dua rakaat karena Allah Ta'ala.",
      tataCara: "Dilakukan 2 rakaat sesudah shalat fardu Maghrib.",
    ),
    SholatSunnah(
      name: "Qabliyah Isya",
      category: "Rawatib",
      niatArab: "أُصَلِّي سُنَّةَ الْعِشَاءِ رَكْعَتَيْنِ قَبْلِيَّةً لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatal 'isyaa-i rak'ataini qabliyyatan lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah sebelum Isya dua rakaat karena Allah Ta'ala.",
      tataCara: "Dilakukan 2 rakaat sebelum shalat fardu Isya.",
    ),
    SholatSunnah(
      name: "Ba'diyyah Isya",
      category: "Rawatib",
      niatArab: "أُصَلِّي سُنَّةَ الْعِشَاءِ رَكْعَتَيْنِ بَعْدِيَّةً لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatal 'isyaa-i rak'ataini ba'diyyatan lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah sesudah Isya dua rakaat karena Allah Ta'ala.",
      tataCara: "Dilakukan 2 rakaat sesudah shalat fardu Isya.",
    ),

    // 2. Salat Sunnah Berdasarkan Waktu/Keadaan
    SholatSunnah(
      name: "Salat Tahajjud",
      category: "Waktu/Keadaan",
      niatArab: "أُصَلِّي سُنَّةَ التَّهَجُّدِ رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatat tahajjudi rak'ataini lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah Tahajjud dua rakaat karena Allah Ta'ala.",
      tataCara: "Dilakukan minimal 2 rakaat pada malam hari setelah bangun tidur. Waktu utama adalah sepertiga malam terakhir.",
      doaAfter: "اللَّهُمَّ لَكَ الْحَمْدُ أَنْتَ قَيِّمُ السَّمَاوَاتِ وَالْأَرْضِ...",
      fadhilah: "Shalat sunnah yang paling utama setelah shalat fardu.",
    ),
    SholatSunnah(
      name: "Salat Dhuha",
      category: "Waktu/Keadaan",
      niatArab: "أُصَلِّي سُنَّةَ الضُّحَى رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatadh dhuhaa rak'ataini lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah Dhuha dua rakaat karena Allah Ta'ala.",
      tataCara: "Dilakukan minimal 2 rakaat di pagi hari (saat matahari naik hingga sebelum Dzuhur).",
      fadhilah: "Sedekah bagi seluruh persendian tubuh dan pembuka pintu rezeki.",
    ),
    SholatSunnah(
      name: "Salat Witir",
      category: "Waktu/Keadaan",
      niatArab: "أُصَلِّي سُنَّةَ الْوِتْرِ ثَلَاثَ رَكَعَاتٍ لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatal witri tsalatsa raka'atin lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah Witir tiga rakaat karena Allah Ta'ala.",
      tataCara: "Dilakukan dengan jumlah rakaat ganjil (1, 3, 5, dst) sebagai penutup shalat malam.",
      fadhilah: "Allah Maha Ganjil dan menyukai shalat ganjil.",
    ),
    SholatSunnah(
      name: "Salat Istikhara",
      category: "Waktu/Keadaan",
      niatArab: "أُصَلِّي سُنَّةَ الاِسْتِخَارَةِ رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatal istikhaarati rak'ataini lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah Istikhara dua rakaat karena Allah Ta'ala.",
      tataCara: "Dilakukan 2 rakaat saat bingung menentukan pilihan dalam urusan penting.",
      fadhilah: "Memohon petunjuk terbaik dari Allah atas sebuah pilihan.",
    ),
    SholatSunnah(
      name: "Salat Hajat",
      category: "Waktu/Keadaan",
      niatArab: "أُصَلِّي سُنَّةَ الْحَاجَةِ رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatal haajati rak'ataini lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah Hajat dua rakaat karena Allah Ta'ala.",
      tataCara: "Dilakukan 2 rakaat ketika memiliki keinginan atau hajat khusus kepada Allah.",
      fadhilah: "Memohon agar keinginan/hajat dikabulkan.",
    ),
    SholatSunnah(
      name: "Salat Taubat",
      category: "Waktu/Keadaan",
      niatArab: "أُصَلِّي سُنَّةَ التَّوْبَةِ رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatat taubati rak'ataini lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah Taubat dua rakaat karena Allah Ta'ala.",
      tataCara: "Dilakukan 2 rakaat setelah melakukan dosa atau merasa bersalah, diikuti istighfar.",
      fadhilah: "Allah akan mengampuni hamba-Nya yang bersungguh-sungguh bertaubat.",
    ),
    SholatSunnah(
      name: "Salat Tahiyatul Masjid",
      category: "Waktu/Keadaan",
      niatArab: "أُصَلِّي سُنَّةَ تَحِيَّةِ الْمَسْجِدِ رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatat tahiyyatul masjidi rak'ataini lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah Tahiyatul Masjid dua rakaat karena Allah Ta'ala.",
      tataCara: "Dilakukan 2 rakaat segera setelah masuk masjid sebelum duduk.",
      fadhilah: "Penghormatan terhadap rumah Allah.",
    ),
    SholatSunnah(
      name: "Salat Istisqa (Minta Hujan)",
      category: "Waktu/Keadaan",
      niatArab: "أُصَلِّي سُنَّةَ الاِسْتِسْقَاءِ رَكْعَتَيْنِ مَأْمُومًا لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatal istisqaa-i rak'ataini ma'muman lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah Istisqa dua rakaat sebagai makmum karena Allah Ta'ala.",
      tataCara: "Dilakukan 2 rakaat secara berjamaah di tanah lapang saat terjadi kekeringan/kemarau panjang.",
      fadhilah: "Memohon diturunkannya hujan kepada Allah SWT.",
    ),

    // 3. Salat Sunnah Berjamaah / Moment Tertentu
    SholatSunnah(
      name: "Salat Tarawih",
      category: "Berjamaah/Momen",
      niatArab: "أُصَلِّي سُنَّةَ التَّرَاوِيحِ رَكْعَتَيْنِ مَأْمُومًا لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatat tarawiihi rak'ataini ma'muman lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah Tarawih dua rakaat sebagai makmum karena Allah Ta'ala.",
      tataCara: "Dilakukan pada malam bulan Ramadhan setelah shalat Isya.",
      fadhilah: "Diampuni dosa-dosa yang telah lalu bagi yang mendirikannya karena iman.",
    ),
    SholatSunnah(
      name: "Salat Idulfitri",
      category: "Berjamaah/Momen",
      niatArab: "أُصَلِّي سُنَّةً لِعِيدِ الْفِطْرِ رَكْعَتَيْنِ مَأْمُومًا لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatal li'idil fithri rak'ataini ma'muman lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah Idulfitri dua rakaat sebagai makmum karena Allah Ta'ala.",
      tataCara: "Dilakukan 2 rakaat pada pagi hari tanggal 1 Syawal secara berjamaah.",
      fadhilah: "Kembali fitrah (suci) setelah berpuasa Ramadhan.",
    ),
    SholatSunnah(
      name: "Salat Iduladha",
      category: "Berjamaah/Momen",
      niatArab: "أُصَلِّي سُنَّةً لِعِيدِ الْأَضْحَى رَكْعَتَيْنِ مَأْمُومًا لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatal li'idil adh-haa rak'ataini ma'muman lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah Iduladha dua rakaat sebagai makmum karena Allah Ta'ala.",
      tataCara: "Dilakukan 2 rakaat pada pagi hari tanggal 10 Zulhijjah secara berjamaah.",
      fadhilah: "Mengingat ketulusan pengorbanan Nabi Ibrahim AS.",
    ),

    // 4. Salat Jenazah & Kondisi Khusus
    SholatSunnah(
      name: "Salat Jenazah",
      category: "Khusus",
      niatArab: "أُصَلِّي عَلَى هَذَا الْمَيِّتِ أَرْبَعَ تَكْبِيرَاتٍ فَرْضَ كِفَايَةٍ مَأْمُومًا لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli 'ala hadzal mayyiti arba'a takbiratin fardha kifayatin ma'muman lillahi ta'ala.",
      niatTranslation: "Aku niat shalat atas jenazah ini empat takbir fardu kifayah sebagai makmum karena Allah Ta'ala.",
      tataCara: "Dilakukan dengan 4 takbir tanpa ruku' dan sujud dalam posisi berdiri.",
      fadhilah: "Mendapat pahala sebesar satu qirath (sebesar gunung Uhud) jika menshalatkannya.",
    ),
    SholatSunnah(
      name: "Salat Jamak & Qashar",
      category: "Khusus",
      niatArab: "أُصَلِّي فَرْضَ الظُّهْرِ مَجْمُوعًا إِلَيْهِ الْعَصْرُ جَمْعَ تَقْدِيمٍ قَصْرًا لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli fardhadz dhuhri majmuu'an ilaihil 'ashru jam'a taqdiimin qashran lillahi ta'ala.",
      niatTranslation: "Aku niat shalat fardu Dzuhur dijamak dengan Ashar jamak takdim diqashar karena Allah Ta'ala.",
      tataCara: "Meringkas shalat 4 rakaat menjadi 2 rakaat (Qashar) dan menggabungkan dua shalat fardu dalam satu waktu (Jamak). Khusus untuk musafir.",
      fadhilah: "Rukhshah (keringanan) dari Allah bagi hamba-Nya yang dalam perjalanan.",
    ),

    // 5. Bacaan & Dzikir Sholat
    SholatSunnah(
      name: "Bacaan Takbiratul Ihram",
      category: "Bacaan & Dzikir",
      niatArab: "اللهُ أَكْبَرُ",
      niatLatin: "Allahu Akbar.",
      niatTranslation: "Allah Maha Besar.",
      tataCara: "Diucapkan sambil mengangkat kedua tangan mengawali shalat.",
    ),
    SholatSunnah(
      name: "Doa Iftitah",
      category: "Bacaan & Dzikir",
      niatArab: "اللَّهُ أَكْبَرُ كَبِيرًا وَالْحَمْدُ لِلَّهِ كَثِيرًا وَسُبْحَانَ اللَّهِ بُكْرَةً وَأَصِيلاً. إِنِّي وَجَّهْتُ وَجْهِيَ لِلَّذِي فَطَرَ السَّمَاوَاتِ وَالْأَرْضَ حَنِيفًا مُسْلِمًا وَمَا أَنَا مِنَ الْمُشْرِكِينَ",
      niatLatin: "Allahu akbar kabira walhamdu lillahi katsira wa subhanallahi bukrataw wa ashila...",
      niatTranslation: "Allah Maha Besar dengan sebesar-besarnya. Segala puji yang sebanyak-banyaknya bagi Allah. Dan Maha Suci Allah siang dan malam.",
      tataCara: "Dibaca setelah takbiratul ihram pada rakaat pertama.",
    ),
    SholatSunnah(
      name: "Bacaan Ruku",
      category: "Bacaan & Dzikir",
      niatArab: "سُبْحَانَ رَبِّيَ الْعَظِيمِ وَبِحَمْدِهِ",
      niatLatin: "Subhana rabbiyal 'adhimi wa bihamdihi (3x).",
      niatTranslation: "Maha Suci Tuhanku Yang Maha Agung dan dengan segala puji bagi-Nya.",
      tataCara: "Dibaca 3x saat posisi ruku'.",
    ),
    SholatSunnah(
      name: "Bacaan Sujud",
      category: "Bacaan & Dzikir",
      niatArab: "سُبْحَانَ رَبِّيَ الْأَعْلَى وَبِحَمْدِهِ",
      niatLatin: "Subhana rabbiyal a'la wa bihamdihi (3x).",
      niatTranslation: "Maha Suci Tuhanku Yang Maha Tinggi dan dengan segala puji bagi-Nya.",
      tataCara: "Dibaca 3x saat posisi sujud.",
    ),
    SholatSunnah(
      name: "Duduk di Antara Dua Sujud",
      category: "Bacaan & Dzikir",
      niatArab: "رَبِّ اغْفِرْ لِي وَارْحَمْنِي وَاجْبُرْنِي وَارْفَعْنِي وَارْزُقْنِي وَاهْدِنِي وَعَافِنِي وَاعْفُ عَنِّي",
      niatLatin: "Rabbighfirli warhamni wajburni warfa'ni warzuqni wahdini wa'afini wa'fu 'anni.",
      niatTranslation: "Ya Allah, ampunilah aku, kasihanilah aku, cukupilah aku, angkatlah derajatku, berilah aku rezeki, berilah aku petunjuk, berilah aku kesehatan, dan ampunilah aku.",
      tataCara: "Dibaca saat posisi duduk di antara dua sujud.",
    ),
    SholatSunnah(
      name: "Doa Qunut (Subuh)",
      category: "Bacaan & Dzikir",
      niatArab: "اللَّهُمَّ اهْدِنِي فِيمَنْ هَدَيْتَ، وَعَافِنِي فِيمَنْ عَافَيْتَ، وَتَوَلَّنِي فِيمَنْ تَوَلَّيْتَ، وَبَارِكْ لِي فِيمَا أَعْطَيْتَ...",
      niatLatin: "Allahummah dini fiiman hadait, wa 'aafini fiiman 'aafait...",
      niatTranslation: "Ya Allah, berilah aku petunjuk di antara orang-orang yang Engkau beri petunjuk, dan berilah aku keselamatan...",
      tataCara: "Dibaca pada rakaat kedua shalat Subuh saat posisi iktidal.",
    ),
    SholatSunnah(
      name: "Dzikir Setelah Shalat (Istighfar & Salam)",
      category: "Bacaan & Dzikir",
      niatArab: "أَسْتَغْفِرُ اللهَ (3x) . اَللَّهُمَّ أَنْتَ السَّلاَمُ، وَمِنْكَ السَّلاَمُ، تَبَارَكْتَ يَا ذَا الْجَلاَلِ وَاْلإِكْرَامِ",
      niatLatin: "Astaghfirullah (3x). Allahumma antas salaam wa minkas salaam...",
      niatTranslation: "Aku memohon ampun kepada Allah (3x). Ya Allah, Engkau Mahasejahtera, dari-Mu lah kesejahteraan...",
      tataCara: "Dibaca segera setelah salam.",
    ),
  ];
}
