class SholatSunnah {
  final String name;
  final String category;
  final String niatArab;
  final String niatLatin;
  final String niatTranslation;
  final String tataCara;
  final String? doaAfter;
  final String? fadhilah;

  SholatSunnah({
    required this.name,
    required this.category,
    required this.niatArab,
    required this.niatLatin,
    required this.niatTranslation,
    required this.tataCara,
    this.doaAfter,
    this.fadhilah,
  });
}

class SholatSunnahData {
  static List<SholatSunnah> sunnahList = [
    // 0. Salat Wajib
    SholatSunnah(
      name: "Salat Subuh",
      category: "Salat Wajib",
      niatArab: "أُصَلِّي فَرْضَ الصُّبْحِ رَكْعَتَيْنِ مُسْتَقْبِلَ الْقِبْلَةِ أَدَاءً لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli fardhash shubhi rak'ataini mustaqbilal qiblati ada'an lillahi ta'ala.",
      niatTranslation: "Aku niat melakukan shalat fardhu subuh dua rakaat, sambil menghadap kiblat, saat ini, karena Allah ta'ala.",
      tataCara: "2 Rakaat dengan Qunut (opsional).",
    ),
    SholatSunnah(
      name: "Salat Dzuhur",
      category: "Salat Wajib",
      niatArab: "أُصَلِّي فَرْضَ الظُّهْرِ أَرْبَعَ رَكَعَاتٍ مُسْتَقْبِلَ الْقِبْلَةِ أَدَاءً لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli fardhadz dzuhri arba'a raka'atin mustaqbilal qiblati ada'an lillahi ta'ala.",
      niatTranslation: "Aku niat melakukan shalat fardhu dzuhur empat rakaat, sambil menghadap kiblat, saat ini, karena Allah ta'ala.",
      tataCara: "4 Rakaat dengan suara pelan (Sirr).",
    ),
    SholatSunnah(
      name: "Salat Ashar",
      category: "Salat Wajib",
      niatArab: "أُصَلِّي فَرْضَ الْعَصْرِ أَرْبَعَ رَكَعَاتٍ مُسْتَقْبِلَ الْقِبْلَةِ أَدَاءً لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli fardhal 'ashri arba'a raka'atin mustaqbilal qiblati ada'an lillahi ta'ala.",
      niatTranslation: "Aku niat melakukan shalat fardhu ashar empat rakaat, sambil menghadap kiblat, saat ini, karena Allah ta'ala.",
      tataCara: "4 Rakaat dengan suara pelan (Sirr).",
    ),
    SholatSunnah(
      name: "Salat Maghrib",
      category: "Salat Wajib",
      niatArab: "أُصَلِّي فَرْضَ الْمَغْرِبِ ثَلاثَ رَكَعَاتٍ مُسْتَقْبِلَ الْقِبْلَةِ أَدَاءً لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli fardhal maghribi tsalatsa raka'atin mustaqbilal qiblati ada'an lillahi ta'ala.",
      niatTranslation: "Aku niat melakukan shalat fardhu maghrib tiga rakaat, sambil menghadap kiblat, saat ini, karena Allah ta'ala.",
      tataCara: "3 Rakaat dengan suara keras (Jahr) di 2 rakaat pertama.",
    ),
    SholatSunnah(
      name: "Salat Isya",
      category: "Salat Wajib",
      niatArab: "أُصَلِّي fَرْضَ الْعِشَاءِ أَرْبَعَ رَكَعَاتٍ مُسْتَقْبِلَ الْقِبْلَةِ أَدَاءً لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli fardhal 'isyaa-i arba'a raka'atin mustaqbilal qiblati ada'an lillahi ta'ala.",
      niatTranslation: "Aku niat melakukan shalat fardhu isya empat rakaat, sambil menghadap kiblat, saat ini, karena Allah ta'ala.",
      tataCara: "4 Rakaat dengan suara keras (Jahr) di 2 rakaat pertama.",
    ),
    // 1. Salat Sunnah Rawatib
    SholatSunnah(
      name: "Qabliyah Subuh",
      category: "Rawatib",
      niatArab: "أُصَلِّي سُنَّةَ الصُّبْحِ رَكْعَتَيْنِ قَبْلِيَّةً لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatash shubhi rak'ataini qabliyyatan lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah sebelum Subuh dua rakaat karena Allah Ta'ala.",
      tataCara: "Dilakukan 2 rakaat sebelum shalat fardu Subuh.",
      fadhilah: "Lebih baik dari dunia dan seisinya.",
    ),
    SholatSunnah(
      name: "Qabliyah Dzuhur",
      category: "Rawatib",
      niatArab: "أُصَلِّي سُنَّةَ الظُّهْرِ رَكْعَتَيْنِ قَبْلِيَّةً لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatadh dhuhri rak'ataini qabliyyatan lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah sebelum Dzuhur dua rakaat karena Allah Ta'ala.",
      tataCara: "Dilakukan 2 atau 4 rakaat sebelum shalat fardu Dzuhur.",
      fadhilah: "Mengharamkan diri dari api neraka.",
    ),
    SholatSunnah(
      name: "Ba'diyyah Dzuhur",
      category: "Rawatib",
      niatArab: "أُصَلِّي سُنَّةَ الظُّهْرِ رَكْعَتَيْنِ بَعْدِيَّةً لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatadh dhuhri rak'ataini ba'diyyatan lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah sesudah Dzuhur dua rakaat karena Allah Ta'ala.",
      tataCara: "Dilakukan 2 atau 4 rakaat sesudah shalat fardu Dzuhur.",
      fadhilah: "Menyempurnakan kekurangan pada shalat fardu.",
    ),
    SholatSunnah(
      name: "Qabliyah Ashar",
      category: "Rawatib",
      niatArab: "أُصَلِّي سُنَّةَ الْعَصْرِ رَكْعَتَيْنِ قَبْلِيَّةً لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatal 'ashri rak'ataini qabliyyatan lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah sebelum Ashar dua rakaat karena Allah Ta'ala.",
      tataCara: "Dilakukan 2 atau 4 rakaat sebelum shalat fardu Ashar.",
      fadhilah: "Mendapat rahmat Allah.",
    ),
    SholatSunnah(
      name: "Qabliyah Maghrib",
      category: "Rawatib",
      niatArab: "أُصَلِّي سُنَّةَ الْمَغْرِبِ رَكْعَتَيْنِ قَبْلِيَّةً لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatal maghribi rak'ataini qabliyyatan lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah sebelum Maghrib dua rakaat karena Allah Ta'ala.",
      tataCara: "Dilakukan 2 rakaat sebelum shalat fardu Maghrib.",
    ),
    SholatSunnah(
      name: "Ba'diyyah Maghrib",
      category: "Rawatib",
      niatArab: "أُصَلِّي سُنَّةَ الْمَغْرِبِ رَكْعَتَيْنِ بَعْدِيَّةً لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatal maghribi rak'ataini ba'diyyatan lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah sesudah Maghrib dua rakaat karena Allah Ta'ala.",
      tataCara: "Dilakukan 2 rakaat sesudah shalat fardu Maghrib.",
    ),
    SholatSunnah(
      name: "Qabliyah Isya",
      category: "Rawatib",
      niatArab: "أُصَلِّي سُنَّةَ الْعِشَاءِ رَكْعَتَيْنِ قَبْلِيَّةً لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatal 'isyaa-i rak'ataini qabliyyatan lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah sebelum Isya dua rakaat karena Allah Ta'ala.",
      tataCara: "Dilakukan 2 rakaat sebelum shalat fardu Isya.",
    ),
    SholatSunnah(
      name: "Ba'diyyah Isya",
      category: "Rawatib",
      niatArab: "أُصَلِّي سُنَّةَ الْعِشَاءِ رَكْعَتَيْنِ بَعْدِيَّةً لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatal 'isyaa-i rak'ataini ba'diyyatan lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah sesudah Isya dua rakaat karena Allah Ta'ala.",
      tataCara: "Dilakukan 2 rakaat sesudah shalat fardu Isya.",
    ),

    // 2. Salat Sunnah Berdasarkan Waktu/Keadaan
    SholatSunnah(
      name: "Salat Tahajjud",
      category: "Waktu/Keadaan",
      niatArab: "أُصَلِّي سُنَّةَ التَّهَجُّدِ رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatat tahajjudi rak'ataini lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah Tahajjud dua rakaat karena Allah Ta'ala.",
      tataCara: "Dilakukan minimal 2 rakaat pada malam hari setelah bangun tidur. Waktu utama adalah sepertiga malam terakhir.",
      doaAfter: "اللَّهُمَّ لَكَ الْحَمْدُ أَنْتَ قَيِّمُ السَّمَاوَاتِ وَالْأَرْضِ...",
      fadhilah: "Shalat sunnah yang paling utama setelah shalat fardu.",
    ),
    SholatSunnah(
      name: "Salat Dhuha",
      category: "Waktu/Keadaan",
      niatArab: "أُصَلِّي سُنَّةَ الضُّحَى رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatadh dhuhaa rak'ataini lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah Dhuha dua rakaat karena Allah Ta'ala.",
      tataCara: "Dilakukan minimal 2 rakaat di pagi hari (saat matahari naik hingga sebelum Dzuhur).",
      fadhilah: "Sedekah bagi seluruh persendian tubuh dan pembuka pintu rezeki.",
    ),
    SholatSunnah(
      name: "Salat Witir",
      category: "Waktu/Keadaan",
      niatArab: "أُصَلِّي سُنَّةَ الْوِتْرِ ثَلَاثَ رَكَعَاتٍ لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatal witri tsalatsa raka'atin lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah Witir tiga rakaat karena Allah Ta'ala.",
      tataCara: "Dilakukan dengan jumlah rakaat ganjil (1, 3, 5, dst) sebagai penutup shalat malam.",
      fadhilah: "Allah Maha Ganjil dan menyukai shalat ganjil.",
    ),
    SholatSunnah(
      name: "Salat Istikhara",
      category: "Waktu/Keadaan",
      niatArab: "أُصَلِّي سُنَّةَ الاِسْتِخَارَةِ رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatal istikhaarati rak'ataini lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah Istikhara dua rakaat karena Allah Ta'ala.",
      tataCara: "Dilakukan 2 rakaat saat bingung menentukan pilihan dalam urusan penting.",
      fadhilah: "Memohon petunjuk terbaik dari Allah atas sebuah pilihan.",
    ),
    SholatSunnah(
      name: "Salat Hajat",
      category: "Waktu/Keadaan",
      niatArab: "أُصَلِّي سُنَّةَ الْحَاجَةِ رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatal haajati rak'ataini lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah Hajat dua rakaat karena Allah Ta'ala.",
      tataCara: "Dilakukan 2 rakaat ketika memiliki keinginan atau hajat khusus kepada Allah.",
      fadhilah: "Memohon agar keinginan/hajat dikabulkan.",
    ),
    SholatSunnah(
      name: "Salat Taubat",
      category: "Waktu/Keadaan",
      niatArab: "أُصَلِّي سُنَّةَ التَّوْبَةِ رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatat taubati rak'ataini lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah Taubat dua rakaat karena Allah Ta'ala.",
      tataCara: "Dilakukan 2 rakaat setelah melakukan dosa atau merasa bersalah, diikuti istighfar.",
      fadhilah: "Allah akan mengampuni hamba-Nya yang bersungguh-sungguh bertaubat.",
    ),
    SholatSunnah(
      name: "Salat Tahiyatul Masjid",
      category: "Waktu/Keadaan",
      niatArab: "أُصَلِّي سُنَّةَ تَحِيَّةِ الْمَسْجِدِ رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatat tahiyyatul masjidi rak'ataini lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah Tahiyatul Masjid dua rakaat karena Allah Ta'ala.",
      tataCara: "Dilakukan 2 rakaat segera setelah masuk masjid sebelum duduk.",
      fadhilah: "Penghormatan terhadap rumah Allah.",
    ),

    // 3. Salat Sunnah Berjamaah / Moment Tertentu
    SholatSunnah(
      name: "Salat Tarawih",
      category: "Berjamaah/Momen",
      niatArab: "أُصَلِّي سُنَّةَ التَّرَاوِيحِ رَكْعَتَيْنِ مَأْمُومًا لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatat tarawiihi rak'ataini ma'muman lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah Tarawih dua rakaat sebagai makmum karena Allah Ta'ala.",
      tataCara: "Dilakukan pada malam bulan Ramadhan setelah shalat Isya.",
      fadhilah: "Diampuni dosa-dosa yang telah lalu bagi yang mendirikannya karena iman.",
    ),
    SholatSunnah(
      name: "Salat Idulfitri",
      category: "Berjamaah/Momen",
      niatArab: "أُصَلِّي سُنَّةً لِعِيدِ الْفِطْرِ رَكْعَتَيْنِ مَأْمُومًا لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatal li'idil fithri rak'ataini ma'muman lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah Idulfitri dua rakaat sebagai makmum karena Allah Ta'ala.",
      tataCara: "Dilakukan 2 rakaat pada pagi hari tanggal 1 Syawal secara berjamaah.",
      fadhilah: "Kembali fitrah (suci) setelah berpuasa Ramadhan.",
    ),
    SholatSunnah(
      name: "Salat Iduladha",
      category: "Berjamaah/Momen",
      niatArab: "أُصَلِّي سُنَّةً لِعِيدِ الْأَضْحَى رَكْعَتَيْنِ مَأْمُومًا لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatal li'idil adh-haa rak'ataini ma'muman lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah Iduladha dua rakaat sebagai makmum karena Allah Ta'ala.",
      tataCara: "Dilakukan 2 rakaat pada pagi hari tanggal 10 Zulhijjah secara berjamaah.",
      fadhilah: "Mengingat ketulusan pengorbanan Nabi Ibrahim AS.",
    ),
    SholatSunnah(
      name: "Salat Gerhana (Kusuf & Khusuf)",
      category: "Berjamaah/Momen",
      niatArab: "أُصَلِّي سُنَّةَ لِكُسُوفِ الشَّمْسِ رَكْعَتَيْنِ مَأْمُومًا لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatal likusuufish syamsi rak'ataini ma'muman lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah gerhana matahari dua rakaat sebagai makmum karena Allah Ta'ala.",
      tataCara: "Dilakukan 2 rakaat dengan masing-masing rakaat memiliki 2 ruku' dan 2 bacaan Al-Fatihah. Disunnahkan dilakukan secara berjamaah saat terjadi momen gerhana matahari atau bulan.",
      fadhilah: "Tanda kebesaran Allah SWT.",
    ),
    SholatSunnah(
      name: "Salat Istisqa",
      category: "Berjamaah/Momen",
      niatArab: "أُصَلِّي سُنَّةَ الاِسْتِسْقَاءِ رَكْعَتَيْنِ مَأْمُومًا لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli sunnatal istisqaa-i rak'ataini ma'muman lillahi ta'ala.",
      niatTranslation: "Aku niat shalat sunnah Istisqa dua rakaat sebagai makmum karena Allah Ta'ala.",
      tataCara: "Dilakukan 2 rakaat secara berjamaah di tanah lapang pada momen musim kemarau panjang untuk memohon hujan.",
      fadhilah: "Memohon pertolongan Allah dari kekeringan.",
    ),
    SholatSunnah(
      name: "Salat Jenazah",
      category: "Berjamaah/Momen",
      niatArab: "أُصَلِّي عَلَى هَذَا الْمَيِّتِ أَرْبَعَ تَكْبِيرَاتٍ فَرْضَ كِفَايَةٍ مَأْمُومًا لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli 'ala hadzal mayyiti arba'a takbiratin fardha kifayatin ma'muman lillahi ta'ala.",
      niatTranslation: "Aku niat shalat atas jenazah ini empat takbir fardu kifayah sebagai makmum karena Allah Ta'ala.",
      tataCara: "Salat yang hukumnya fardhu kifayah dan umumnya dilakukan secara berjemaah saat ada momentum pengurusan jenazah. Terdiri dari 4 takbir tanpa ruku' dan sujud.",
      fadhilah: "Pahala satu Qirath bagi yang menshalatkannya.",
    ),
    SholatSunnah(
      name: "Salat Jumat",
      category: "Berjamaah/Momen",
      niatArab: "أُصَلِّي فَرْضَ الْجُمُعَةِ رَكْعَتَيْنِ مُسْتَقْبِلَ الْقِبْلَةِ أَدَاءً مَأْمُومًا لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli fardhal jumu'ati rak'ataini mustaqbilal qiblati ada'an ma'muman lillahi ta'ala.",
      niatTranslation: "Aku niat shalat fardu Jumat dua rakaat menghadap kiblat sebagai makmum karena Allah Ta'ala.",
      tataCara: "Salat wajib pengganti Zuhur bagi laki-laki yang secara mutlak wajib didirikan secara berjemaah. Terdiri dari 2 rakaat dan diawali dengan dua khutbah.",
    ),

    // 4. Salat Kondisi Khusus
    SholatSunnah(
      name: "Salat Jamak & Qashar",
      category: "Khusus",
      niatArab: "أُصَلِّي فَرْضَ الظُّهْرِ مَجْمُوعًا إِلَيْهِ الْعَصْرُ جَمْعَ تَقْدِيمٍ قَصْرًا لِلَّهِ تَعَالَى",
      niatLatin: "Ushalli fardhadz dhuhri majmuu'an ilaihil 'ashru jam'a taqdiimin qashran lillahi ta'ala.",
      niatTranslation: "Aku niat shalat fardu Dzuhur dijamak dengan Ashar jamak takdim diqashar karena Allah Ta'ala.",
      tataCara: "Meringkas shalat 4 rakaat menjadi 2 rakaat (Qashar) dan menggabungkan dua shalat fardu dalam satu waktu (Jamak). Khusus untuk musafir.",
      fadhilah: "Rukhshah (keringanan) dari Allah bagi hamba-Nya yang dalam perjalanan.",
    ),

    // 5. Bacaan & Dzikir Sholat
    SholatSunnah(
      name: "Bacaan Takbiratul Ihram",
      category: "Bacaan & Dzikir",
      niatArab: "اللهُ أَكْبَرُ",
      niatLatin: "Allahu Akbar.",
      niatTranslation: "Allah Maha Besar.",
      tataCara: "Diucapkan sambil mengangkat kedua tangan mengawali shalat.",
    ),
    SholatSunnah(
      name: "Doa Iftitah",
      category: "Bacaan & Dzikir",
      niatArab: "اللَّهُ أَكْبَرُ كَبِيرًا وَالْحَمْدُ لِلَّهِ كَثِيرًا وَسُبْحَانَ اللَّهِ بُكْرَةً وَأَصِيلاً. إِنِّي وَجَّهْتُ وَجْهِيَ لِلَّذِي فَطَرَ السَّمَاوَاتِ وَالْأَرْضَ حَنِيفًا مُسْلِمًا وَمَا أَنَا مِنَ الْمُشْرِكِينَ. إِنَّ صَلَاتِي وَنُسُكِي وَمَحْيَايَ وَمَمَاتِي لِلَّهِ رَبِّ الْعَالَمِينَ. لَا شَرِيكَ لَهُ وَبِذَٰلِكَ أُمِرْتُ وَأَنَا مِنَ الْمُسْلِمِينَ",
      niatLatin: "Allahu akbar kabira walhamdu lillahi katsira wa subhanallahi bukrataw wa ashila. Inni wajjahtu wajhiya lilladzi fatharas samawati wal ardha hanifam muslimaw wa ma ana minal musyrikin. Inna shalati wa nusuki wa mahyaya wa mamati lillahi rabbil 'alamin...",
      niatTranslation: "Allah Maha Besar dengan sebesar-besarnya. Segala puji bagi Allah sebanyak-banyaknya. Sesungguhnya aku hadapkan wajahku kepada Zat yang telah menciptakan langit dan bumi dengan penuh kelurusan dan kepasrahan...",
      tataCara: "Dibaca setelah takbiratul ihram pada rakaat pertama.",
    ),
    SholatSunnah(
      name: "Surah Al-Fatihah",
      category: "Bacaan & Dzikir",
      niatArab: "بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ. الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ. الرَّحْمَنِ الرَّحِيمِ. مَالِكِ يَوْمِ الدِّينِ. إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ. اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ. صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ",
      niatLatin: "Bismillaahir rohmaanir rohiim. Alhamdu lillaahi robbil 'aalamiin. Ar-rohmaanir rohiim. Maaliki yaumid diin. Iyyaaka na'budu wa iyyaaka nasta'iin. Ihdinash shiroothol mustaqiim...",
      niatTranslation: "Dengan nama Allah Yang Maha Pengasih, Maha Penyayang. Segala puji bagi Allah, Tuhan seluruh alam...",
      tataCara: "Wajib dibaca pada setiap rakaat dalam shalat.",
    ),
    SholatSunnah(
      name: "Bacaan Ruku",
      category: "Bacaan & Dzikir",
      niatArab: "سُبْحَانَ رَبِّيَ الْعَظِيمِ وَبِحَمْدِهِ",
      niatLatin: "Subhana rabbiyal 'adhimi wa bihamdihi (3x).",
      niatTranslation: "Maha Suci Tuhanku Yang Maha Agung dan dengan segala puji bagi-Nya.",
      tataCara: "Dibaca 3x saat posisi ruku'.",
    ),
    SholatSunnah(
      name: "Bacaan I'tidal & Doanya",
      category: "Bacaan & Dzikir",
      niatArab: "سَمِعَ اللهُ لِمَنْ حَمِدَهُ. رَبَّنَا لَكَ الْحَمْدُ مِلْءَ السَّمَاوَاتِ وَمِلْءَ الْأَرْضِ وَمِلْءَ مَا شِئْتَ مِنْ شَيْءٍ بَعْدُ",
      niatLatin: "Sami'allahu liman hamidah. Rabbana lakal hamdu mil'as samawati wa mil'al ardhi wa mil'a ma syi'ta min syai'in ba'du.",
      niatTranslation: "Allah mendengar orang yang memuji-Nya. Wahai Tuhan kami, bagi-Mu segala puji sepenuh langit dan sepenuh bumi...",
      tataCara: "Dibaca saat bangkit dari ruku' (I'tidal) dan saat posisi berdiri tegak.",
    ),
    SholatSunnah(
      name: "Bacaan Sujud",
      category: "Bacaan & Dzikir",
      niatArab: "سُبْحَانَ رَبِّيَ الْأَعْلَى وَبِحَمْدِهِ",
      niatLatin: "Subhana rabbiyal a'la wa bihamdihi (3x).",
      niatTranslation: "Maha Suci Tuhanku Yang Maha Tinggi dan dengan segala puji bagi-Nya.",
      tataCara: "Dibaca 3x saat posisi sujud.",
    ),
    SholatSunnah(
      name: "Duduk di Antara Dua Sujud",
      category: "Bacaan & Dzikir",
      niatArab: "رَبِّ اغْفِرْ لِي وَارْحَمْنِي وَاجْبُرْنِي وَارْفَعْنِي وَارْزُقْنِي وَاهْدِنِي وَعَافِنِي وَاعْفُ عَنِّي",
      niatLatin: "Rabbighfirli warhamni wajburni warfa'ni warzuqni wahdini wa'afini wa'fu 'anni.",
      niatTranslation: "Ya Allah, ampunilah aku, kasihanilah aku, cukupilah aku, angkatlah derajatku, berilah aku rezeki, berilah aku petunjuk, berilah aku kesehatan, dan ampunilah aku.",
      tataCara: "Dibaca saat posisi duduk di antara dua sujud.",
    ),
    SholatSunnah(
      name: "Tahiyat Awal (Lengkap)",
      category: "Bacaan & Dzikir",
      niatArab: "التَّحِيَّاتُ الْمُبَارَكَاتُ الصَّلَوَاتُ الطَّيِّبَاتُ لِلَّهِ، السَّلَامُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ، السَّلَامُ عَلَيْنَا وَعَلَى عِبَادِ اللَّهِ الصَّالِحِينَ، أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ، وَأَشْهَدُ أَنَّ مُحَمَّدًا رَسُولُ اللَّهِ. اللَّهُمَّ صَلِّ عَلَى سَيِّدِنَا مُحَمَّدٍ",
      niatLatin: "Attahiyyatul mubarakatush shalawatuth thayyibatu lillah. Assalamu 'alaika ayyuhan nabiyyu wa rahmatullahi wa barakatuh. Assalamu 'alaina wa 'ala 'ibadillahish shalihin. Asyhadu alla ilaha illallah, wa asyhadu anna Muhammadar Rasulullah. Allahumma shalli 'ala sayyidina Muhammad.",
      niatTranslation: "Segala penghormatan yang penuh berkah, rahmat, dan kebaikan adalah milik Allah. Semoga keselamatan, rahmat Allah, dan berkah-Nya tetap tercurahkan kepadamu, wahai Nabi. Semoga keselamatan tetap tercurahkan kepada kami dan kepada hamba-hamba Allah yang saleh. Aku bersaksi bahwa tidak ada tuhan selain Allah, dan aku bersaksi bahwa Muhammad adalah utusan Allah. Ya Allah, limpahkanlah rahmat kepada Nabi Muhammad.",
      tataCara: "Dibaca pada rakaat kedua shalat yang lebih dari dua rakaat.",
    ),
    SholatSunnah(
      name: "Tahiyat Akhir & Shalawat Ibrahimiyah",
      category: "Bacaan & Dzikir",
      niatArab: "التَّحِيَّاتُ الْمُبَارَكَاتُ الصَّلَوَاتُ الطَّيِّبَاتُ لِلَّهِ، السَّلَامُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ، السَّلَامُ عَلَيْنَا وَعَلَى عِبَادِ اللَّهِ الصَّالِحِينَ، أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ، وَأَشْهَدُ أَنَّ مُحَمَّدًا رَسُولُ اللَّهِ. اللَّهُمَّ صَلِّ عَلَى سَيِّدِنَا مُحَمَّدٍ وَعَلَى آلِ سَيِّدِنَا مُحَمَّدٍ، كَمَا صَلَّيْتَ عَلَى سَيِّدِنَا إِبْرَاهِيمَ وَعَلَى آلِ سَيِّدِنَا إِبْرَاهِيمَ، وَبَارِكْ عَلَى سَيِّدِنَا مُحَمَّدٍ وَعَلَى آلِ سَيِّدِنَا مُحَمَّدٍ، كَمَا بَارَكْتَ عَلَى سَيِّدِنَا إِبْرَاهِيمَ وَعَلَى آلِ سَيِّدِنَا إِبْرَاهِيمَ، فِي الْعَالَمِينَ إِنَّكَ حَمِيدٌ مَجِيدٌ",
      niatLatin: "Attahiyyatul mubarakatush shalawatuth thayyibatu lillah... Allahumma shalli 'ala sayyidina Muhammad wa 'ala ali sayyidina Muhammad, kama shallaita 'ala sayyidina Ibrahim... wa barik 'ala sayyidina Muhammad... kama barakta 'ala sayyidina Ibrahim... fil 'alamina innaka hamidum majid.",
      niatTranslation: "Segala penghormatan... Ya Allah, limpahkanlah rahmat kepada Nabi Muhammad dan keluarganya, sebagaimana Engkau telah melimpahkan rahmat kepada Nabi Ibrahim dan keluarganya... Sesungguhnya Engkau Maha Terpuji lagi Maha Mulia.",
      tataCara: "Dibaca pada rakaat terakhir sebelum salam.",
    ),
    SholatSunnah(
      name: "Salam",
      category: "Bacaan & Dzikir",
      niatArab: "السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللهِ",
      niatLatin: "Assalamu 'alaikum wa rahmatullah.",
      niatTranslation: "Semoga keselamatan dan rahmat Allah tercurah kepadamu.",
      tataCara: "Diucapkan sambil menoleh ke kanan lalu ke kiri untuk mengakhiri shalat.",
    ),
    SholatSunnah(
      name: "Doa Qunut Subuh (Lengkap)",
      category: "Bacaan & Dzikir",
      niatArab: "اللَّهُمَّ اهْدِنِي فِيمَنْ هَدَيْتَ، وَعَافِنِي فِيمَنْ عَافَيْتَ، وَتَوَلَّنِي فِيمَنْ تَوَلَّيْتَ، وَبَارِكْ لِي فِيمَا أَعْطَيْتَ، وَقِنِي شَرَّ مَا قَضَيْتَ، فَإِنَّكَ تَقْضِي وَلَا يُقْضَى عَلَيْكَ، وَإِنَّهُ لَا يَذِلُّ مَنْ وَالَيْتَ، وَلَا يَعِزُّ مَنْ عَادَيْتَ، تَبَارَكْتَ رَبَّنَا وَتَعَالَيْتَ، فَلَكَ الْحَمْدُ عَلَى مَا قَضَيْتَ، أَسْتَغْفِرُكَ وَأَتُوبُ إِلَيْكَ، وَصَلَّى اللهُ عَلَى سَيِّدِنَا مُحَمَّدٍ النَّبِيِّ الْأُمِّيِّ وَعَلَى آلِهِ وَصَحْبِهِ وَسَلَّمَ",
      niatLatin: "Allahummah-dinii fii man hadait, wa 'aafinii fii man 'aafait, wa tawallanii fii man tawallait, wa baarik lii fii maa a'thait, wa qinii syarra maa qadhait, fa innaka taqdhii wa laa yuqdhaa 'alaik...",
      niatTranslation: "Ya Allah, berilah aku petunjuk... Engkaulah yang menghukum dan tidak dihukum... Segala puji bagi-Mu atas apa yang Engkau putuskan. Aku memohon ampun dan bertaubat kepada-Mu...",
      tataCara: "Dibaca pada rakaat kedua shalat Subuh saat posisi iktidal.",
    ),
    SholatSunnah(
      name: "Dzikir Setelah Shalat",
      category: "Bacaan & Dzikir",
      niatArab: "أَسْتَغْفِرُ اللهَ (3x) . اَللَّهُمَّ أَنْتَ السَّلاَمُ، وَمِنْكَ السَّلاَمُ، تَبَارَكْتَ يَا ذَا الْجَلاَلِ وَاْلإِكْرَامِ",
      niatLatin: "Astaghfirullah (3x). Allahumma antas salaam wa minkas salaam, tabaarakta yaa dzal jalaali wal ikroom.",
      niatTranslation: "Aku memohon ampun kepada Allah (3x). Ya Allah, Engkau Mahasejahtera, dari-Mu lah kesejahteraan, Maha Berkah Engkau wahai Zat yang memiliki kebesaran dan kemuliaan.",
      tataCara: "Dibaca segera setelah salam.",
    ),
  ];
}
